# Generated by Django 3.1.7 on 2021-04-25 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeeditor.directory')),
            ],
            options={
                'verbose_name_plural': 'Directories',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('directory', models.ForeignKey(blank=True, limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeeditor.directory')),
                ('owner', models.ForeignKey(limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Section categories',
            },
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Section statuses',
            },
        ),
        migrations.CreateModel(
            name='SectionStatusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(limit_choices_to={'available': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Section statuses' data",
            },
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.CharField(max_length=1000000)),
                ('is_subsection', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('parent_file', models.ForeignKey(blank=True, limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeeditor.file')),
                ('parent_section', models.ForeignKey(blank=True, limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='codeeditor.filesection')),
                ('section_category', models.ForeignKey(limit_choices_to={'available': True}, on_delete=django.db.models.deletion.CASCADE, to='codeeditor.sectioncategory')),
                ('section_status', models.ForeignKey(limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeeditor.sectionstatus')),
                ('section_status_data', models.OneToOneField(limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='codeeditor.sectionstatusdata')),
            ],
        ),
    ]
