# Generated by Django 3.1.7 on 2021-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesection',
            name='content',
        ),
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.FileField(default=1, upload_to='upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesection',
            name='begin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesection',
            name='end',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
