# Generated by Django 3.1.7 on 2021-04-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0005_auto_20210427_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='vcs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Vc',
        ),
    ]
